name: Changelog Update

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'

      - name: Install conventional-changelog-cli
        run: npm install -g conventional-changelog-cli

      - name: Generate changelog
        run: |
          git fetch --unshallow || git fetch origin main:main
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0
          cat CHANGELOG.md

      - name: Commit and push changelog update
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md" || echo "No changes to commit"
          git push origin main
