name: Changelog Update

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

permissions: write-all

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install conventional-changelog-cli
        run: npm install -g conventional-changelog-cli

      - name: Simulate commit for PR title
        run: |
          # Format PR title as a conventional commit message
          echo "${{ github.event.pull_request.title }}" > temp_message.txt
          # Temporarily commit this message
          git commit --allow-empty -F temp_message.txt

      - name: Generate changelog
        run: |
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0
          cat CHANGELOG.md

      - name: Revert temporary commit
        run: git reset HEAD~

      - name: Commit and push changelog update
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md based on PR #${{ github.event.pull_request.number }} title"
          git push origin HEAD:refs/heads/${{ github.head_ref }}
